// Seed script to populate menu items in MongoDB
import './config/env.js';
import { connectDB } from './config/db.js';
import Menu from './models/Menu.js';

const sampleMenus = [
  // Restaurant 1: Allergy-Safe Bistro
  {
    restaurantName: 'Allergy-Safe Bistro',
    category: 'appetizer',
    itemName: 'Gluten-Free Bruschetta',
    description: 'Crispy gluten-free bread topped with fresh tomatoes, basil, and olive oil',
    price: 399,
    imageUrl: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Allergy-Safe Bistro',
    category: 'main',
    itemName: 'Gluten-Free Pasta Primavera',
    description: 'Fresh vegetables tossed with gluten-free pasta in a light garlic sauce',
    price: 649,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Allergy-Safe Bistro',
    category: 'main',
    itemName: 'Grilled Salmon with Quinoa',
    description: 'Fresh Atlantic salmon with quinoa and steamed vegetables',
    price: 899,
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=300',
    allergenInfo: ['fish'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Allergy-Safe Bistro',
    category: 'dessert',
    itemName: 'Vegan Chocolate Cake',
    description: 'Rich chocolate cake made with plant-based ingredients',
    price: 299,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Allergy-Safe Bistro',
    category: 'beverage',
    itemName: 'Fresh Fruit Smoothie',
    description: 'Blend of seasonal fruits with coconut milk',
    price: 249,
    imageUrl: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },

  // Restaurant 2: Safe Eats Cafe
  {
    restaurantName: 'Safe Eats Cafe',
    category: 'appetizer',
    itemName: 'Nut-Free Hummus Platter',
    description: 'Creamy hummus served with fresh vegetables and pita bread',
    price: 429,
    imageUrl: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=300',
    allergenInfo: ['sesame'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Safe Eats Cafe',
    category: 'main',
    itemName: 'Dairy-Free Pizza Margherita',
    description: 'Classic pizza with dairy-free cheese and fresh basil',
    price: 599,
    imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=300',
    allergenInfo: ['gluten'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Safe Eats Cafe',
    category: 'main',
    itemName: 'Grilled Chicken Bowl',
    description: 'Grilled chicken with rice, vegetables, and tahini sauce',
    price: 699,
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=300',
    allergenInfo: ['sesame'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Safe Eats Cafe',
    category: 'side',
    itemName: 'Sweet Potato Fries',
    description: 'Crispy sweet potato fries with dairy-free aioli',
    price: 249,
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Safe Eats Cafe',
    category: 'dessert',
    itemName: 'Coconut Panna Cotta',
    description: 'Creamy coconut dessert with berry compote',
    price: 329,
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },

  // Restaurant 3: Green Leaf Kitchen
  {
    restaurantName: 'Green Leaf Kitchen',
    category: 'appetizer',
    itemName: 'Avocado Toast',
    description: 'Smashed avocado on whole grain toast with cherry tomatoes',
    price: 449,
    imageUrl: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=300',
    allergenInfo: ['gluten'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Green Leaf Kitchen',
    category: 'main',
    itemName: 'Vegan Buddha Bowl',
    description: 'Quinoa, roasted vegetables, chickpeas, and tahini dressing',
    price: 549,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300',
    allergenInfo: ['sesame'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Green Leaf Kitchen',
    category: 'main',
    itemName: 'Mushroom Risotto',
    description: 'Creamy arborio rice with wild mushrooms (dairy-free option available)',
    price: 749,
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-c4f6c8f6c42e?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Green Leaf Kitchen',
    category: 'beverage',
    itemName: 'Green Detox Juice',
    description: 'Fresh blend of kale, cucumber, apple, and lemon',
    price: 299,
    imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Green Leaf Kitchen',
    category: 'dessert',
    itemName: 'Chia Seed Pudding',
    description: 'Chia seeds in coconut milk with fresh berries',
    price: 279,
    imageUrl: 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },

  // Restaurant 4: Urban Grill House
  {
    restaurantName: 'Urban Grill House',
    category: 'appetizer',
    itemName: 'Chicken Wings',
    description: 'Crispy wings with choice of sauce (gluten-free)',
    price: 499,
    imageUrl: 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=300',
    allergenInfo: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Urban Grill House',
    category: 'main',
    itemName: 'Classic Burger',
    description: 'Beef burger with lettuce, tomato, and gluten-free bun option',
    price: 599,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=300',
    allergenInfo: ['gluten'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Urban Grill House',
    category: 'main',
    itemName: 'Grilled Steak',
    description: 'Premium ribeye steak with roasted vegetables',
    price: 1299,
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=300',
    allergenInfo: [],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Urban Grill House',
    category: 'side',
    itemName: 'Loaded Baked Potato',
    description: 'Baked potato with dairy-free toppings',
    price: 279,
    imageUrl: 'https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Urban Grill House',
    category: 'beverage',
    itemName: 'Craft Beer',
    description: 'Selection of local craft beers',
    price: 299,
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=300',
    allergenInfo: ['gluten'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },

  // Additional 20 Menu Items with Perfect Images
  
  // Restaurant 5: Spice Garden
  {
    restaurantName: 'Spice Garden',
    category: 'appetizer',
    itemName: 'Spring Rolls',
    description: 'Crispy vegetable spring rolls with sweet chili sauce',
    price: 349,
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=300',
    allergenInfo: ['gluten'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Spice Garden',
    category: 'main',
    itemName: 'Paneer Tikka Masala',
    description: 'Grilled cottage cheese in rich tomato-based curry',
    price: 549,
    imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=300',
    allergenInfo: ['dairy'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Spice Garden',
    category: 'main',
    itemName: 'Biryani Bowl',
    description: 'Fragrant basmati rice with vegetables and aromatic spices',
    price: 449,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Spice Garden',
    category: 'dessert',
    itemName: 'Gulab Jamun',
    description: 'Traditional Indian sweet dumplings in sugar syrup',
    price: 249,
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=300',
    allergenInfo: ['dairy', 'gluten'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Spice Garden',
    category: 'beverage',
    itemName: 'Mango Lassi',
    description: 'Refreshing yogurt-based mango drink',
    price: 199,
    imageUrl: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?w=300',
    allergenInfo: ['dairy'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },

  // Restaurant 6: Ocean Breeze Cafe
  {
    restaurantName: 'Ocean Breeze Cafe',
    category: 'appetizer',
    itemName: 'Calamari Rings',
    description: 'Crispy fried squid rings with tartar sauce',
    price: 499,
    imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=300',
    allergenInfo: ['seafood', 'gluten'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Ocean Breeze Cafe',
    category: 'main',
    itemName: 'Fish and Chips',
    description: 'Beer-battered fish with crispy fries',
    price: 649,
    imageUrl: 'https://images.unsplash.com/photo-1579208575657-c595a05383b7?w=300',
    allergenInfo: ['fish', 'gluten'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Ocean Breeze Cafe',
    category: 'main',
    itemName: 'Prawn Pasta',
    description: 'Creamy garlic prawns with fettuccine pasta',
    price: 749,
    imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=300',
    allergenInfo: ['seafood', 'gluten', 'dairy'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Ocean Breeze Cafe',
    category: 'side',
    itemName: 'Coleslaw',
    description: 'Fresh cabbage salad with creamy dressing',
    price: 179,
    imageUrl: 'https://images.unsplash.com/photo-1625938145312-559bf0d7f39b?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Ocean Breeze Cafe',
    category: 'dessert',
    itemName: 'Tiramisu',
    description: 'Classic Italian coffee-flavored dessert',
    price: 399,
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=300',
    allergenInfo: ['dairy', 'eggs', 'gluten'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },

  // Restaurant 7: The Breakfast Club
  {
    restaurantName: 'The Breakfast Club',
    category: 'main',
    itemName: 'Pancake Stack',
    description: 'Fluffy pancakes with maple syrup and berries',
    price: 399,
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=300',
    allergenInfo: ['gluten', 'dairy', 'eggs'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'The Breakfast Club',
    category: 'main',
    itemName: 'Eggs Benedict',
    description: 'Poached eggs on English muffin with hollandaise sauce',
    price: 449,
    imageUrl: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=300',
    allergenInfo: ['eggs', 'dairy', 'gluten'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'The Breakfast Club',
    category: 'main',
    itemName: 'French Toast',
    description: 'Golden brioche with cinnamon and powdered sugar',
    price: 379,
    imageUrl: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=300',
    allergenInfo: ['gluten', 'eggs', 'dairy'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'The Breakfast Club',
    category: 'beverage',
    itemName: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice',
    price: 149,
    imageUrl: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'The Breakfast Club',
    category: 'side',
    itemName: 'Hash Browns',
    description: 'Crispy golden potato hash browns',
    price: 199,
    imageUrl: 'https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },

  // Restaurant 8: Mediterranean Delight
  {
    restaurantName: 'Mediterranean Delight',
    category: 'appetizer',
    itemName: 'Falafel Platter',
    description: 'Crispy chickpea fritters with tahini sauce',
    price: 399,
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=300',
    allergenInfo: ['sesame'],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Mediterranean Delight',
    category: 'main',
    itemName: 'Greek Salad',
    description: 'Fresh vegetables with feta cheese and olives',
    price: 449,
    imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=300',
    allergenInfo: ['dairy'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
  },
  {
    restaurantName: 'Mediterranean Delight',
    category: 'main',
    itemName: 'Shawarma Wrap',
    description: 'Grilled chicken wrapped in pita with garlic sauce',
    price: 499,
    imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=300',
    allergenInfo: ['gluten', 'dairy'],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Mediterranean Delight',
    category: 'dessert',
    itemName: 'Baklava',
    description: 'Sweet pastry with nuts and honey',
    price: 299,
    imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=300',
    allergenInfo: ['nuts', 'gluten'],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
  },
  {
    restaurantName: 'Mediterranean Delight',
    category: 'beverage',
    itemName: 'Mint Lemonade',
    description: 'Refreshing lemonade with fresh mint',
    price: 179,
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=300',
    allergenInfo: [],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
  },
];

const seedMenus = async () => {
  try {
    // Connect to database
    await connectDB();

    console.log('🌱 Starting menu seed...');

    // Clear existing menus
    await Menu.deleteMany({});
    console.log('✅ Cleared existing menu items');

    // Insert sample menus
    const createdMenus = await Menu.insertMany(sampleMenus);
    console.log(`✅ Successfully seeded ${createdMenus.length} menu items`);

    // Show summary by restaurant
    const restaurants = [...new Set(sampleMenus.map(m => m.restaurantName))];
    console.log('\n📊 Menu Summary:');
    for (const restaurant of restaurants) {
      const count = sampleMenus.filter(m => m.restaurantName === restaurant).length;
      console.log(`   ${restaurant}: ${count} items`);
    }

    console.log('\n🎉 Menu seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding menus:', error);
    process.exit(1);
  }
};

// Run the seed function
seedMenus();
